Added method to reassign ownership for Postgres multi-user-rotation.
aws-samples/aws-secrets-manager-rotation-lambdas pull request #43
Opened 2020-06-19 14:53 UTC by FloWi

I created an alternative solution to the ownership problem for the multi-user-rotation.
The solution provided by @thekevinbrown in issue #39 didn't work in our case.

https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/pull/39#issuecomment-646551901

*Issue #, if available:*
Issue #38 
*Description of changes:*
I found an easy way to transfer ownership of all objects created by one user to another and created this PR. I didn't have a chance to test this yet, since I didn't have time to set up a local environment. Do you have a test-environment for your rotation-lambdas?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-17 20:54 UTC, xsnrg commented
@FloWi Did you find another path to solve this, or are you just using your branch code for the lambda? 

This is a needed fix. 

@followben and @madsid

2020-11-19 09:27 UTC, FloWi commented
@xsnrg I think we discarded this feature for now because of this bug. We're not live yet so no need for password rotation.

2020-11-20 13:49 UTC, selfvin requested changes

2020-11-20 17:35 UTC, FloWi commented on SecretsManagerRDSPostgreSQLRotationMultiUser/lambda_function.py
> +            cur.execute("REASSIGN OWNED BY %s TO %s" % (current_owner_dict['username'], new_owner_username))
Sure thing. Thanks for the hint!

2020-11-20 17:36 UTC, FloWi commented on SecretsManagerRDSPostgreSQLRotationMultiUser/lambda_function.py
> +            cur.execute("REASSIGN OWNED BY %s TO %s" % (current_owner_dict['username'], new_owner_username))
Let's see if anyone at aws cares about that stuff :)

2022-12-09 23:30 UTC, closed without merging